DROP TABLE CHAT;
DROP TABLE ROOM;
DROP SEQUENCE ROOM_SEQ;
DROP SEQUENCE CHAT_SEQ;

CREATE SEQUENCE ROOM_SEQ;
CREATE SEQUENCE CHAT_SEQ;

CREATE TABLE ROOM (
	ROOM_SEQ NUMBER	PRIMARY KEY
    , USER_ID VARCHAR(20) REFERENCES USER_INFO
	, NAME VARCHAR(200)
	, INDATE DATE
    , USER_COUNT NUMBER
);

CREATE TABLE CHAT (
	CHAT_SEQ NUMBER PRIMARY KEY
	, ROOM_SEQ	 NUMBER REFERENCES ROOM
    , USER_ID VARCHAR(20)
    , MESSAGE VARCHAR(1000)
    , INDATE DATE
);

SELECT * FROM USER_INFO;